'''Generate a small HTML page from what the user types.

Open the produced index.html in a browser afterwards.
'''


def save_html(html: str, filename: str = 'index.html') -> None:
    'Write the HTML text into a file.'
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(html)


def main() -> None:
    user_input = input('Enter your name: ')

    html = f'''<!doctype html>
<html>
  <head><meta charset="utf-8"><title>Welcome</title></head>
  <body>
    <h1>Welcome {user_input}!</h1>
    <p>This page was generated by Python.</p>
  </body>
</html>
'''

    save_html(html)
    print('index.html was created.')


if __name__ == '__main__':
    main()
