# By default two objects are equal only when they are the SAME object.
# __eq__ lets us compare the content instead.
from functools import total_ordering


@total_ordering          # generates <=, >, >= out of __eq__ and __lt__
class Student:
    def __init__(self, name: str, score: float) -> None:
        self.name = name
        self.score = score

    def __repr__(self) -> str:
        return f'Student({self.name!r}, {self.score})'

    def __eq__(self, other) -> bool:
        # Always check the type: comparing with something else must not crash.
        if not isinstance(other, Student):
            return NotImplemented
        return self.score == other.score

    def __lt__(self, other) -> bool:
        if not isinstance(other, Student):
            return NotImplemented
        return self.score < other.score

    def __hash__(self) -> int:
        '''Defining __eq__ removes the default __hash__, so the object can no
        longer go into a set or be a dict key. We give it back here.'''
        return hash(self.score)


if __name__ == '__main__':
    a = Student('Ali', 18)
    b = Student('Sara', 20)
    c = Student('Reza', 18)

    print(a == c)        # True  - same score
    print(a < b)         # True
    print(b >= a)        # True  - generated by total_ordering

    students = [b, a, c]
    print(sorted(students))
    print(max(students))

    print({a, b, c})     # works thanks to __hash__
